# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 709)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.display_video_frame = QtWidgets.QFrame(self.centralWidget)
        self.display_video_frame.setGeometry(QtCore.QRect(290, 260, 671, 431))
        self.display_video_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.display_video_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.display_video_frame.setObjectName("display_video_frame")
        self.display_video_label = QtWidgets.QLabel(self.display_video_frame)
        self.display_video_label.setGeometry(QtCore.QRect(10, 10, 651, 411))
        self.display_video_label.setText("")
        self.display_video_label.setObjectName("display_video_label")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(390, 70, 301, 32))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.grou_box_controls = QtWidgets.QGroupBox(self.centralWidget)
        self.grou_box_controls.setGeometry(QtCore.QRect(50, 70, 181, 131))
        self.grou_box_controls.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grou_box_controls.setAlignment(QtCore.Qt.AlignCenter)
        self.grou_box_controls.setObjectName("grou_box_controls")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.grou_box_controls)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 160, 95))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.start_pushbutton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Jenson Pro Lt Disp")
        font.setPointSize(12)
        self.start_pushbutton.setFont(font)
        self.start_pushbutton.setObjectName("start_pushbutton")
        self.verticalLayout_2.addWidget(self.start_pushbutton)
        self.stop_pushbutton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Jenson Pro Lt Disp")
        font.setPointSize(12)
        self.stop_pushbutton.setFont(font)
        self.stop_pushbutton.setObjectName("stop_pushbutton")
        self.verticalLayout_2.addWidget(self.stop_pushbutton)
        self.quit_pushbutton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Jenson Pro Lt Disp")
        font.setPointSize(12)
        self.quit_pushbutton.setFont(font)
        self.quit_pushbutton.setObjectName("quit_pushbutton")
        self.verticalLayout_2.addWidget(self.quit_pushbutton)
        self.group_box_results_panel = QtWidgets.QGroupBox(self.centralWidget)
        self.group_box_results_panel.setGeometry(QtCore.QRect(20, 210, 241, 481))
        self.group_box_results_panel.setAlignment(QtCore.Qt.AlignCenter)
        self.group_box_results_panel.setObjectName("group_box_results_panel")
        self.display_statistics_label = QtWidgets.QLabel(self.group_box_results_panel)
        self.display_statistics_label.setGeometry(QtCore.QRect(10, 30, 221, 111))
        self.display_statistics_label.setText("")
        self.display_statistics_label.setObjectName("display_statistics_label")
        self.listWidget = QtWidgets.QListWidget(self.group_box_results_panel)
        self.listWidget.setGeometry(QtCore.QRect(10, 160, 221, 141))
        self.listWidget.setObjectName("listWidget")
        self.tableView = QtWidgets.QTableView(self.group_box_results_panel)
        self.tableView.setGeometry(QtCore.QRect(10, 310, 221, 161))
        self.tableView.setObjectName("tableView")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(740, 170, 221, 81))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 30, 131, 42))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.date_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.date_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.date_label.setText("")
        self.date_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.date_label.setObjectName("date_label")
        self.gridLayout.addWidget(self.date_label, 3, 0, 1, 1)
        self.time_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.time_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time_label.setText("")
        self.time_label.setObjectName("time_label")
        self.gridLayout.addWidget(self.time_label, 4, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 61, 42))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.description_text_time = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.description_text_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.description_text_time.setObjectName("description_text_time")
        self.verticalLayout.addWidget(self.description_text_time)
        self.description_text_date = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.description_text_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.description_text_date.setObjectName("description_text_date")
        self.verticalLayout.addWidget(self.description_text_date)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(770, 50, 181, 81))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logo_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("images/logo.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_3.addWidget(self.logo_label)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ATTENDANCE MANAGEMENT SYSTEM"))
        self.grou_box_controls.setTitle(_translate("MainWindow", "CONTROLS"))
        self.start_pushbutton.setText(_translate("MainWindow", "START"))
        self.stop_pushbutton.setText(_translate("MainWindow", "STOP"))
        self.quit_pushbutton.setText(_translate("MainWindow", "QUIT"))
        self.group_box_results_panel.setTitle(_translate("MainWindow", "RESULTS PANEL"))
        self.groupBox.setTitle(_translate("MainWindow", "TIME AND DATE"))
        self.description_text_time.setText(_translate("MainWindow", "Date   :"))
        self.description_text_date.setText(_translate("MainWindow", "Time   :"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
