# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 779)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.display_video_frame = QtWidgets.QFrame(self.centralWidget)
        self.display_video_frame.setGeometry(QtCore.QRect(290, 180, 671, 431))
        self.display_video_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.display_video_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.display_video_frame.setObjectName("display_video_frame")
        self.display_video_label = QtWidgets.QLabel(self.display_video_frame)
        self.display_video_label.setGeometry(QtCore.QRect(10, 10, 651, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.display_video_label.sizePolicy().hasHeightForWidth())
        self.display_video_label.setSizePolicy(sizePolicy)
        self.display_video_label.setMinimumSize(QtCore.QSize(3, 3))
        self.display_video_label.setText("")
        self.display_video_label.setObjectName("display_video_label")
        self.grou_box_controls = QtWidgets.QGroupBox(self.centralWidget)
        self.grou_box_controls.setGeometry(QtCore.QRect(20, 20, 241, 131))
        self.grou_box_controls.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grou_box_controls.setAlignment(QtCore.Qt.AlignCenter)
        self.grou_box_controls.setObjectName("grou_box_controls")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.grou_box_controls)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 221, 95))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.start_pushbutton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Jenson Pro Lt Disp")
        font.setPointSize(12)
        self.start_pushbutton.setFont(font)
        self.start_pushbutton.setObjectName("start_pushbutton")
        self.verticalLayout_2.addWidget(self.start_pushbutton)
        self.quit_pushbutton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Jenson Pro Lt Disp")
        font.setPointSize(12)
        self.quit_pushbutton.setFont(font)
        self.quit_pushbutton.setObjectName("quit_pushbutton")
        self.verticalLayout_2.addWidget(self.quit_pushbutton)
        self.stop_pushbutton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Jenson Pro Lt Disp")
        font.setPointSize(12)
        self.stop_pushbutton.setFont(font)
        self.stop_pushbutton.setObjectName("stop_pushbutton")
        self.verticalLayout_2.addWidget(self.stop_pushbutton)
        self.group_box_results_panel = QtWidgets.QGroupBox(self.centralWidget)
        self.group_box_results_panel.setGeometry(QtCore.QRect(20, 160, 241, 601))
        self.group_box_results_panel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.group_box_results_panel.setObjectName("group_box_results_panel")
        self.table_widget = QtWidgets.QTableWidget(self.group_box_results_panel)
        self.table_widget.setGeometry(QtCore.QRect(10, 30, 221, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_widget.sizePolicy().hasHeightForWidth())
        self.table_widget.setSizePolicy(sizePolicy)
        self.table_widget.setMinimumSize(QtCore.QSize(4, 4))
        self.table_widget.setMaximumSize(QtCore.QSize(221, 561))
        self.table_widget.setBaseSize(QtCore.QSize(221, 411))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_widget.setFont(font)
        self.table_widget.setGridStyle(QtCore.Qt.NoPen)
        self.table_widget.setRowCount(25)
        self.table_widget.setColumnCount(3)
        self.table_widget.setObjectName("table_widget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.table_widget.setHorizontalHeaderItem(2, item)
        self.table_widget.horizontalHeader().setVisible(True)
        self.table_widget.horizontalHeader().setCascadingSectionResizes(False)
        self.table_widget.horizontalHeader().setDefaultSectionSize(72)
        self.table_widget.horizontalHeader().setMinimumSectionSize(20)
        self.table_widget.horizontalHeader().setSortIndicatorShown(False)
        self.table_widget.verticalHeader().setVisible(False)
        self.table_widget.verticalHeader().setDefaultSectionSize(12)
        self.table_widget.verticalHeader().setMinimumSectionSize(10)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.group_box_results_panel)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 560, 221, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_number_student = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_number_student.setObjectName("label_number_student")
        self.horizontalLayout_2.addWidget(self.label_number_student)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(290, 80, 221, 81))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 30, 131, 42))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.date_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.date_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.date_label.setText("")
        self.date_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.date_label.setObjectName("date_label")
        self.gridLayout.addWidget(self.date_label, 3, 0, 1, 1)
        self.time_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.time_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time_label.setText("")
        self.time_label.setObjectName("time_label")
        self.gridLayout.addWidget(self.time_label, 4, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 61, 42))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.description_text_time = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.description_text_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.description_text_time.setObjectName("description_text_time")
        self.verticalLayout.addWidget(self.description_text_time)
        self.description_text_date = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.description_text_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.description_text_date.setObjectName("description_text_date")
        self.verticalLayout.addWidget(self.description_text_date)
        self.logo_label = QtWidgets.QLabel(self.centralWidget)
        self.logo_label.setGeometry(QtCore.QRect(710, 70, 251, 91))
        self.logo_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("images/logo.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 620, 671, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 241, 101))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_layout.setContentsMargins(0, 0, 0, 0)
        self.grid_layout.setObjectName("grid_layout")
        self.student_id_line_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.student_id_line_edit.setObjectName("student_id_line_edit")
        self.grid_layout.addWidget(self.student_id_line_edit, 2, 1, 1, 1)
        self.first_name_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.first_name_label.setObjectName("first_name_label")
        self.grid_layout.addWidget(self.first_name_label, 1, 0, 1, 1)
        self.student_id_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.student_id_label.setObjectName("student_id_label")
        self.grid_layout.addWidget(self.student_id_label, 2, 0, 1, 1)
        self.last_name_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.last_name_label.setObjectName("last_name_label")
        self.grid_layout.addWidget(self.last_name_label, 0, 0, 1, 1)
        self.first_name_line_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.first_name_line_edit.setObjectName("first_name_line_edit")
        self.grid_layout.addWidget(self.first_name_line_edit, 1, 1, 1, 1)
        self.last_name_line_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.last_name_line_edit.setObjectName("last_name_line_edit")
        self.grid_layout.addWidget(self.last_name_line_edit, 0, 1, 1, 1)
        self.progress_bar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progress_bar.setGeometry(QtCore.QRect(280, 90, 361, 23))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(280, 50, 361, 29))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_image_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Jenson Pro Lt Disp")
        font.setPointSize(12)
        self.save_image_button.setFont(font)
        self.save_image_button.setObjectName("save_image_button")
        self.horizontalLayout.addWidget(self.save_image_button)
        self.take_image_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Jenson Pro Lt Disp")
        font.setPointSize(12)
        self.take_image_button.setFont(font)
        self.take_image_button.setObjectName("take_image_button")
        self.horizontalLayout.addWidget(self.take_image_button)
        self.registration_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Jenson Pro Lt Disp")
        font.setPointSize(12)
        self.registration_button.setFont(font)
        self.registration_button.setObjectName("registration_button")
        self.horizontalLayout.addWidget(self.registration_button)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.grou_box_controls.setTitle(_translate("MainWindow", "CONTROLS"))
        self.start_pushbutton.setText(_translate("MainWindow", "START"))
        self.quit_pushbutton.setText(_translate("MainWindow", "QUIT"))
        self.stop_pushbutton.setText(_translate("MainWindow", "STOP"))
        self.group_box_results_panel.setTitle(_translate("MainWindow", "RESULTS PANEL"))
        item = self.table_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table_widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "H:M"))
        self.label_number_student.setText(_translate("MainWindow", ""))
        self.groupBox.setTitle(_translate("MainWindow", "TIME AND DATE"))
        self.description_text_time.setText(_translate("MainWindow", "Date   :"))
        self.description_text_date.setText(_translate("MainWindow", "Time   :"))
        self.groupBox_2.setTitle(_translate("MainWindow", "STUDENTS REGISTRATION"))
        self.first_name_label.setText(_translate("MainWindow", "First name"))
        self.student_id_label.setText(_translate("MainWindow", "Student ID"))
        self.last_name_label.setText(_translate("MainWindow", "Last name"))
        self.save_image_button.setText(_translate("MainWindow", "SAVE"))
        self.take_image_button.setText(_translate("MainWindow", "TAKE IMAGE"))
        self.registration_button.setText(_translate("MainWindow", "REGISTRATION"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
